version: "3.9"

services:
  api_gateway:
    build:
      context: ../../api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=supersecretkey
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smarthub_gateway
    depends_on:
      - db

  user_service:
    build:
      context: ../../user_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET=supersecretkey
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smarthub_users
    depends_on:
      - db

  job_service:
    build:
      context: ../../job_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smarthub_jobs
    depends_on:
      - db

  ai_service:
    build:
      context: ../../ai_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  airflow:
    build:
      context: ../airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/airflow
    volumes:
      - ../airflow/dags:/opt/airflow/dags
    depends_on:
      - db
