# --- infra/docker/docker-compose.yml ---
version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smarthub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
